{{- if .Values.serviceAccount.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "smasher.serviceAccountName" . }}
  labels:
    {{- include "smasher.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "smasher.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
{{- end }}