{{- $dot := . }}
{{- if .Values.secrets.create }}
{{- range $s := .Values.secrets.list }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $s.name }}
  namespace: {{ $dot.Release.Namespace }}
  labels:
    app.kubernetes.io/version: {{ $dot.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ $dot.Release.Service }}
    app.kubernetes.io/name: {{ default $dot.Chart.Name $dot.Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ $dot.Release.Name }}
    meta.helm.sh/release-namespace: {{ $dot.Release.Namespace }}
data:
{{- toYaml $s.data | nindent 2 }}
type: {{ $s.type }}
{{- end }}
{{- end }}
