{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "smasher.serviceAccountName" . }}
  labels:
    {{- include "smasher.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.secrets.create }}
secrets:
{{- range $secret := .Values.secrets.list }}
  - name: {{ $secret.name }}
{{- end }}
{{- end }}
{{- end }}
